version: '3'

services:
  front-end:
    container_name: elit-fasad
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - /app/node_modules
